base_url = "https://babilinx.github.io"
title = "Babilinx's home"
description = "Babilinx's website"
compile_sass = true
build_search_index = false
theme = "apollo"
minify_html = true
generate_feeds = true
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = false
highlight_theme = "ayu-light"

[extra]
toc = true
use_cdn = false
#favicon = "/icon/favicon.png"
theme = "toggle"
comment = false
fancy_code = true
dynamic_note = true
repo_url = "https://github.com/babilinx/babilinx.github.io/tree/main/content/"

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    { name = "/tags", url = "/tags", weight = 4 },
]

socials = [
    { name = "matrix", url = "https://matrix.to/#/@papilinux:matrix.org", icon = "matrix" },
    { name = "discord", url = "https://discord.com/users/656158865876058132", icon = "discord" },
    { name = "github", url = "https://github.com/babilinx/", icon = "github" },
    { name = "email", url = "mailto:babilinx.evx1o@simplelogin.com", icon = "email" },
    { name = "feed", url = "atom.xml", icon = "rss" },
]

